Mini-challenges complete
decadevs/mini-challenges-1 pull request #73
Opened 2020-11-05 08:13 UTC by Ebenezer-ebu

2020-11-05 22:46 UTC, bondz requested changes
Remove the hardcoded array length in transpose.

Also, try to give your variables better names and remove the log statements.

2020-11-05 22:46 UTC, bondz commented on src/roman-numerals/index.js
> +console.log(romanToDecimal("I"));
Remove these logs when submitting your PR

2020-11-05 22:46 UTC, bondz commented on src/transpose/index.js
> +    }
Why limit the array's length to less than 10?

That's a hardcode that you have to remove. We want our arrays to have a dynamic length.

2020-11-05 22:46 UTC, bondz commented on src/transpose/index.js
> +]));
Remove these logs when submitting your PR.

2020-11-06 05:41 UTC, Ebenezer-ebu commented
For the transpose i thought we have some condition in the readme
Constraints
1 <= m <= 10.
1 <= n <= 10.


On Thu, Nov 5, 2020 at 11:46 PM Bond <notifications@github.com> wrote:

> *@bondz* requested changes on this pull request.
>
> Remove the hardcoded array length in transpose.
>
> Also, try to give your variables better names and remove the log
> statements.
> ------------------------------
>
> In src/roman-numerals/index.js
> <https://github.com/decadevs/mini-challenges-1/pull/73#discussion_r518415411>
> :
>
> > +
> +  })
> +  if (msg.length > 0) return msg;
> +  let sum = 0;
> +  for(i = 0; i < split.length; i++) {
> +    let char = split[i];
> +    let char2 = split[i+1];
> +      if(val[char] < val[char2]) {
> +      sum -= val[char];
> +      } else {
> +        sum += val[char];
> +      }
> +  }
> +  return sum;
> +}
> +console.log(romanToDecimal("I"));
>
> Remove these logs when submitting your PR
> ------------------------------
>
> In src/transpose/index.js
> <https://github.com/decadevs/mini-challenges-1/pull/73#discussion_r518415903>
> :
>
> > +     if(array.length < 1 || array.length > 10) {
> +      return;
> +    }
> +    if(array[0].length < 1 || array[0].length > 10) {
> +      return;
> +    }
>
> Why limit the array's length to less than 10?
>
> That's a hardcode that you have to remove. We want our arrays to have a
> dynamic length.
> ------------------------------
>
> In src/transpose/index.js
> <https://github.com/decadevs/mini-challenges-1/pull/73#discussion_r518416079>
> :
>
> > +console.log(transpose([
> +  [5, 12, 17, 9, 3],
> +  [13, 4, 8, 14, 1],
> +  [9, 6, 3, 7, 21],
> +]));
>
> Remove these logs when submitting your PR.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/decadevs/mini-challenges-1/pull/73#pullrequestreview-524730904>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM4Q5JS2FOQNXNVVW5FTF5DSOMTMTANCNFSM4TLBC5KQ>
> .
>

2020-11-06 06:14 UTC, Ebenezer-ebu commented
Noted

On Thu, Nov 5, 2020 at 11:46 PM Bond <notifications@github.com> wrote:

> *@bondz* requested changes on this pull request.
>
> Remove the hardcoded array length in transpose.
>
> Also, try to give your variables better names and remove the log
> statements.
> ------------------------------
>
> In src/roman-numerals/index.js
> <https://github.com/decadevs/mini-challenges-1/pull/73#discussion_r518415411>
> :
>
> > +
> +  })
> +  if (msg.length > 0) return msg;
> +  let sum = 0;
> +  for(i = 0; i < split.length; i++) {
> +    let char = split[i];
> +    let char2 = split[i+1];
> +      if(val[char] < val[char2]) {
> +      sum -= val[char];
> +      } else {
> +        sum += val[char];
> +      }
> +  }
> +  return sum;
> +}
> +console.log(romanToDecimal("I"));
>
> Remove these logs when submitting your PR
> ------------------------------
>
> In src/transpose/index.js
> <https://github.com/decadevs/mini-challenges-1/pull/73#discussion_r518415903>
> :
>
> > +     if(array.length < 1 || array.length > 10) {
> +      return;
> +    }
> +    if(array[0].length < 1 || array[0].length > 10) {
> +      return;
> +    }
>
> Why limit the array's length to less than 10?
>
> That's a hardcode that you have to remove. We want our arrays to have a
> dynamic length.
> ------------------------------
>
> In src/transpose/index.js
> <https://github.com/decadevs/mini-challenges-1/pull/73#discussion_r518416079>
> :
>
> > +console.log(transpose([
> +  [5, 12, 17, 9, 3],
> +  [13, 4, 8, 14, 1],
> +  [9, 6, 3, 7, 21],
> +]));
>
> Remove these logs when submitting your PR.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/decadevs/mini-challenges-1/pull/73#pullrequestreview-524730904>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM4Q5JS2FOQNXNVVW5FTF5DSOMTMTANCNFSM4TLBC5KQ>
> .
>

2020-11-06 08:39 UTC, bondz commented
This PR targets the wrong branch. Rather than open another PR, you can edit your PR to change the target branch. Closing.

2020-11-06 08:39 UTC, closed without merging